### ISSUE TITLE
单gpu可以跑吗？

### ISSUE THREAD

**Issue by woshiwoyali** [wusaifei/garbage_classify#22]

**Comment by woshiwoyali** [comment]
执行命令：
python run.py --data_url='../garbage_classify/train_data' --train_url='./model_snapshots' --deploy_script_path='./deploy_scripts'
修改train.py第48行model = multi_gpu_model(model,1)改成1。
添加GPU编号os.environ["CUDA_VISIBLE_DEVICES"] = "0"
运行报错：
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
/home/zjs/Desktop/laji/garbage/train.py:48: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  model = Model(input=model.input, output=predictions)
Traceback (most recent call last):
  File "run.py", line 166, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 157, in main
    train_model(FLAGS)
  File "/home/zjs/Desktop/laji/garbage/train.py", line 90, in train_model
    model = model_fn(FLAGS, objective, optimizer, metrics)
  File "/home/zjs/Desktop/laji/garbage/train.py", line 49, in model_fn
    model = multi_gpu_model(model,1)  # 修改成自身需要的GPU数量，4代表用4个GPU同时加载程序
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/multi_gpu_utils.py", line 165, in multi_gpu_model
    'Received: `gpus=%d`' % gpus)
ValueError: For multi-gpu usage to be effective, call `multi_gpu_model` with `gpus >= 2`. Received: `gpus=1`
请问，在单GPU的模式下，可以运行吗？如果可以依据这个报错，我需要如何修改代码？

**Comment by mars918** [comment]
同问，我的笔记本想跑一一下，跑不起来

**Comment by Aurevious** [comment]
把train.py第48行model = multi_gpu_model(model,1)注释掉就跑通了。

**Comment by Miger0629** [comment]
> 把train.py第48行model = multi_gpu_model(model,1)注释掉就跑通了。

请问你有没有遇到 BrokenPipeError: [Errno 32] Broken pipe 这个问题，有的话是怎么解决的，谢谢

**Comment by cy-dream** [comment]
ValueError: To call `multi_gpu_model` with `gpus=2`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1']. However this machine only has: ['/cpu:0']. Try reducing `gpus`.
我有四个gpu但是不知道为什么出现了这种情况

**Comment by cy-dream** [comment]
ValueError: To call `multi_gpu_model` with `gpus=2`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1']. However this machine only has: ['/cpu:0']. Try reducing `gpus`.
我有两个GPU但是不知道为什么说我没有

**Comment by Super-Alpha** [comment]
> > 把train.py第48行model = multi_gpu_model(model,1)注释掉就跑通了。
> 
> 请问你有没有遇到 BrokenPipeError: [Errno 32] Broken pipe 这个问题，有的话是怎么解决的，谢谢

同问！

**Comment by Jeremy32-ohh** [comment]
> > > 把train.py第48行model = multi_gpu_model(model,1)注释掉就跑通了。
> > 
> > 
> > 请问你有没有遇到 BrokenPipeError: [Errno 32] Broken pipe 这个问题，有的话是怎么解决的，谢谢
> 
> 同问！

 请问 BrokenPipeError: [Errno 32] Broken pipe 这个问题现在解决了吗？我也遇到了，请问怎么解决这个呀？在代码中也找不到num_workers，多数解答都是说把num_workers=0取消多进程即可，但是未找到代码中有这个。
