### ISSUE TITLE
训练结束后进行评估，运作python run.py --mode=eval --eval_pb_path='./model_snapshots/model' --test_data_url='./test_img'报错

### ISSUE THREAD

**Issue by shakey-cuimiao** [wusaifei/garbage_classify#23]
2020-03-10 10:37:34.998582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   N N 
2020-03-10 10:37:34.998708: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10312 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-03-10 10:37:34.998966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10312 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "/opt/shakey/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1092, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "/opt/shakey/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/opt/shakey/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3557, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("input_1:0", shape=(?, 456, 456, 3), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 166, in <module>
    tf.app.run()
  File "/opt/shakey/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 163, in main
    eval_model(FLAGS)
  File "/opt/shakey/imageclass/garbage_classify-master/eval.py", line 215, in eval_model
    test_single_model(FLAGS)
  File "/opt/shakey/imageclass/garbage_classify-master/eval.py", line 159, in test_single_model
    pred_score = sess1.run([output_score], feed_dict={input_images: img})
  File "/opt/shakey/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/opt/shakey/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1095, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("input_1:0", shape=(?, 456, 456, 3), dtype=float32) is not an element of this graph.

**Comment by Aurevious** [comment]
@shakey-cuimiao 朋友，请问你有efficientnet-b5_notop.h5权重吗？我下载了好几天也没成功。

**Comment by Aurevious** [comment]
`  File "D:\DeepLearnning\anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\client\session.py", line 1095, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("input_1:0", shape=(?, 456, 456, 3), dtype=float32) is not an element of this graph.
`
您好，你的问题解决了吗？我遇到了和你相同的问题。

**Comment by jingrunzhou** [comment]
'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("input_1:0", shape=(?, 456, 456, 3), dtype=float32) is not an element of this graph.
同样的问题，大佬解决了吗
