### ISSUE TITLE
找不到指定模块

### ISSUE THREAD

**Issue by prayae** [wusaifei/garbage_classify#47]
你好作者，我按照你的要求安装了所有的环境  但是训练的时候找不到指定模块是怎么回事
“
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    import tensorflow as tf
  File "C:\ProgramData\Anaconda3\envs\tf_1_13_1\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\ProgramData\Anaconda3\envs\tf_1_13_1\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Anaconda3\envs\tf_1_13_1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tf_1_13_1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\envs\tf_1_13_1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\envs\tf_1_13_1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\envs\tf_1_13_1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\envs\tf_1_13_1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。
”

另外我想问一下  这个训练里面的“--train_url='./model_snapshots‘’”是什么意思  没找到这个文件夹

**Comment by wusaifei** [comment]
你好，如果找不到这个文件加可以自己在指定的位置创建一下哈。我的代码里面没有加上自动生成文件夹的代码。
